# Generated by Django 2.2 on 2021-09-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
